---
sudo: required
language: python
python:
  - "3.4"
virtualenv:
  system_site_packages: true
services:
  - docker
before_install:
  - sudo apt-get update
  - deactivate
  - sudo -H pip install ansible docker molecule testinfra cryptography six
script:
  - molecule test
