---
sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install libssl-dev
  - sudo -H python -m pip install ansible docker molecule testinfra==1.16.0
  - sudo python -m pip install six==1.12.0
  - sudo python -m pip install cryptography==2.2.2
script:
  - molecule test
