---
sudo: required
language: python
python:
  - "3.4"
virtualenv:
  system_site_packages: true
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo -H pip install ansible docker molecule testinfra
  - sudo pip install six==1.12.0
script:
  - molecule test
