---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - sudo apt-get update
  - deactivate
  - sudo -H pip install ansible docker molecule testinfra cryptography
script:
  - molecule test
